---
- name: UI - Install monasca-ui package
  pip: name=monasca-ui state=latest
  notify:
    - restart apache

- name: UI - Link dashboard
  file: src={{ ui_src_path }}{{ ui_py_file }} dest={{ ui_dest_path }}{{ ui_py_file }} state=link force=no

- name: UI - Link monitoring directory
  file: src={{ panel_src_path }} dest={{ panel_dest_path }} state=link force=no

- name: UI - Fetch grafana tar.gz file
  get_url: dest=/root/hpcloud-mon-grafana-{{grafana_version}}.tar.gz url={{github_tarball_url}}/{{grafana_version}}
  register: download

- name: UI - Uncompress the grafana tar
  unarchive: copy=no dest={{ grafana_base_dir }} src=/root/hpcloud-mon-grafana-{{grafana_version}}.tar.gz
  register: untar
  when: download | changed
  notify:
    - restart apache

# The dir that the tar is extracted to doesn't always match grafana_version so I have to extract it from the output of the command
- name: UI - Link grafana files
  file: src={{grafana_base_dir}}/{{ untar.check_results.out.splitlines()[0] | dirname }}/src dest={{ grafana_dest }} state=link force=no
  when: untar | changed
  notify:
    - restart apache

- name: UI - Link grafana configuration
  file: src={{ grafana_dest }}/config.monasca.js dest={{ grafana_config }} state=link force=no
  when: untar | changed

- meta: flush_handlers

- name: UI - Update offline compression manifest
  command: python {{ horizon_path }}manage.py compress --force

- name: Enable apache
  service: name=apache2 state=started enabled=yes
